[build]
  command = "composer install --no-dev --optimize-autoloader && APP_ENV=production APP_URL=https://6a54bc6250f9060008ecc9ab--wp-plugin-development.netlify.app ASSET_URL=/ composer build"
  publish = "storage/app/static"